package.json
Doing the `elm-package install` up front is probably not necessary given that the timeout for the individual tests needs to be ridiculously long for Travis anyway.
=> Simplify `npm test` script

examples/compileHelloWorld.js, index.js, package.json
An exported function that sends compiled Elm code out as a string. The api matches with the current one for compile, except there's also a `callback` which will take any errors and the data returned as a buffer.
I also added two examples for this
options.output will be used to figure out if we want to compile to html or js. For example, js would be `main.js`. html would be `index.html
I needed this for `elm-webpack` so that we didn't need to create real files, just get text back.
=> Add the ability to compile to a string

package.json
Trivial, but the `temp` package should've been in dependencies, not devDependencies.
=> Dependency temp should've been in dependencies, not devDepend

index.js, test/compile.js, test/fixtures/Bad.elm
Added tests for bad sources, as I saw an issue with the new `compileToString` method incorrectly resolving when it should reject.
=> Test compilation of bad sources

index.js, test/compile.js, test/fixtures/TypeError.elm
I'm not sure this PR is quite tidy enough to merge, but I wanted to open it for some discussion.
I set up my system to use `webpack-hot-middleware` along with `elm-loader` and `elm-hot-loader`, Hot middleware has an enhanced client which can show build errors in-page in an overlay. The current implementation didn't provide an error object from `compileToString` that worked with this.
This PR changes the error result to be an `Error` object, and populates it with the output from `elm-make`. Annoyingly, because this is no longer a tty, we lose colour (see https://github.com/elm-lang/elm-make/issues/73)
Here's what the changes look like in action:
=> Include error details in exception

.gitignore, .travis.yml, README.md, appveyor.yml, bower.json, examples/HelloWorld.elm, examples/elm-package.json, package.json, test/compile.js, test/fixtures/Bad.elm, test/fixtures/Parent.elm, test/fixtures/ParentWithNestedDeps.elm, test/fixtures/Test/ChildA.elm, test/fixtures/Test/ChildB.elm, test/fixtures/Test/Sample/NestedChild.elm, test/fixtures/TypeError.elm, test/fixtures/elm-package.json
Now all tests run 0.17 code. Descriptions no longer claim to support 0.15 or 0.16, although in practice they will probably still work fine.
=> Update for 0.17

test/compile.js, worker.js
This makes the tests pass, and also avoids a module loading error on initialisation.
=> Fix usage of temp module in the worker

index.js
The main benefit of this change is that the `elm-make` warnings can be seen when both `warn` and `verbose` options are set to true.
=> Log elm-make output in verbose mode

test/dependencies.js, test/fixtures/SimplestMain.elm
The `getBaseDir` function fails for main elm files that do not have an explicit module statement in the first line, such as the most basic possible hello world program.
The failing test results in the following error being thrown:
```
1) #findAllDependencies works for a main file without an explicit module statement:
Error: the string "/home/michael/code/bugfix/node-elm-compiler/test/fixtures/SimplestMain.elm is not a syntactically valid Elm module. Try running elm-make on it manually to figure out what the problem is." was thrown, throw an Error :)
```
The contents of SimplestMain.elm is
```
import Html
main =
Html.text "Hello, World!"
```
This is clearly a valid Elm program, and running elm-make on it manually will succeed.
I arrived at this issue by following the source from …
=> add failing test for most basic hello world app

index.js, test/compile.js
Using `cleanupSync` can cause issues when it's running almost parallel (in the same process).
Our webpack build sometimes failed when it was building multiple entries.
The error that appeared was:
```diff
- Error: ENOENT: no such file or directory, open '/var/folders/2m/_vk4gq8n1m7_b9pr6qxj_qdr0000gn/T/116829-61023-1u5ns37.js'
```
`temp.cleanupSync` removes all tempfiles instead of just the one which isn't used anymore.
As it appears `temp.track()` doesn't have this problem, because it calls `cleanupSync` when the process exits. I added a test which shows the error.
I opened a second PR #40 to show how it fails.
=> use temp.track instead of cleanupSync

index.js
In prep for 0.18, so that folks can use elm-webpack-loader with `"elm-webpack?debug"` and it'll just work
=> add debug flag

.travis.yml, package.json
`echo` used in shell on Travis CI was not writing the elm-make script properly. `printf` has more consistent behavior across shells, and is therefore a more reliable choice.
Fixes #48.
=> Fix CI builds

package.json
This enables `node-elm-compiler#findElmDependencies` to correctly report all dependencies within a multi-source-directory project.
We need this for our Webpack build at Culture Amp, so I’m hoping this can be merged and a new version of node-elm-compiler released to NPM soon, so that we can then upgrade https://github.com/elm-community/elm-webpack-loader.
Thanks in advance!
=> Upgrade to find-elm-dependencies 1.0.1

index.js
Arguments passed to spawn do not need to be  (and should not be) escaped.
This fixes https://github.com/rtfeldman/node-test-runner/issues/147
=> Remove unnecessary path escaping

package.json
`1.0.1` -> `1.0.2` - only change is `find-elm-dependencies` added a `.npmignore`
=> Upgrade find-elm-dependencies

index.js, test/compileToStringSync.js
This adds a new helper `compileToStringSync` and closes #60. Some
use-cases, such as Jest, require a synchronous compilation step, so this
allows Elm code to be compiled synchronously to a string.
=> Add compileToStringSync

index.js
Hello, grunt-elm module can't propagate spawn function to node-elm-compiler module because it's put into options but it's not get used.
Please see this issue: https://github.com/rtfeldman/grunt-elm/issues/14
=> Fixed issue when spawn function could not be propagated from the outside world

index.js, test/compile.js
Enabling these flags allows for tuning the GHC runtime and can dramatically improve build times when a lot of files have to be recompiled, as well as improving performance on large `case` statements, the main benefit is reducing the time spent in the garbage collector.
This does require a version of `elm-make` compiled with the `-rtsopts` option to allow [runtime control](https://downloads.haskell.org/~ghc/7.10.1/docs/html/users_guide/runtime-control.html), if you try to run it on a version without that enabled you'll get the message:
```
$ elm-make src/elm/Main.elm +RTS -A128M -N128M -n8m -RTS
elm-make.exe: Most RTS options are disabled. Link with -rtsopts to enable them.
```
Some further information and related issues here:
- https://github.com/elm-lang/elm-make/issues/159#issuecomment-3 …
=> Add support for +RTS/-RTS flags from GHC

index.js, test/compile.js
以前の引数の渡し方では、意図通りにelm-makeが動作しませんでした。
↓ english from google
In the previous method of passing arguments, elm-make did not work as intended.
=> Fix rts rts flag

index.js
Hi,
I made a small modification for adding support for the new `--optimize` flag in Elm 0.19 (based on the already existing 0.19 branch on this repo).
I also made a PR on [`find-elm-dependencies`](https://github.com/NoRedInk/find-elm-dependencies/pull/8) that might be necessary to go through before merging this one.
This upgrade is necessary for upgrading [`elm-webpack-loader`](https://github.com/elm-community/elm-webpack-loader) to 0.19 ([See PR #142 there](https://github.com/elm-community/elm-webpack-loader/pull/142)).
=> Support Elm 0.19's --optimize flag

index.js
This should report helpful errors when using the warn or pathToMake option.
I tried to test it, but still get this error:
=> Add errors with explanation for the removed options warn and pathToMake

src/index.ts, test/compile.ts, test/compileToStringSync.ts
`compileToString(Sync)` break when the `options.output` field is a path. They expect only a suffix.
This PR fixes this behavior by accepting paths and extracting the suffix.
=> Fix suffix handling in output option

package.json
Using `&` parallely runs both sides of the command. Using `&&` chains them.
=> Prevent parallel executions in scripts

package-lock.json, package.json
The version of lodash we were using has a known vulnerability. This updates us to a version where this vulnerability has been fixed.
Vulnerability details:
https://github.com/NoRedInk/haskell-monorepo/network/alert/tutorials/elm/package-lock.json/lodash/open
=> Update lodash to address security vulnerability

.travis.yml, appveyor.yml
Notes:
- `elm@0.19.0-bugfix2` doesn't work with node 12
- https://github.com/rtfeldman/node-elm-compiler/pull/98/commits/a634874347dfa0f4fd98454cb4ed360bc1d5767f greatly speeds up MacOS travis builds (cutting them from 5 minutes down to 45 seconds)
- `elm@0.19.0-no-deps` does not appear to provide 32-bit Windows binaries
- `elm@0.19.0-no-deps` fails the "works when run multiple times" test on Windows, so I switched it back down to `elm@0.19.0-bugfix6`
=> Add node 12 to CI builds

README.md, package-lock.json, package.json
Fix CVE-2020-8203 by upgrading `lodash` and `find-elm-dependencies` packages (the previously pinned version is vulnerable too). Also, remove version pinning for those two packages to avoid such problems in the future.
Closes #100, Fixes #96
=> Fix CVE-2020-8203, and do not pin find-elm-dependencies and lodash deps.
