rtfeldman/node-elm-compiler

- index.js
related to https://github.com/elm-lang/elm-compiler/issues/914
> force LANG if it's not set in environment

- bower.json
- package.json
> Upgrade to Elm 0.15.1

- README.md
- examples/HelloWorld.elm
- index.js
- package.json
(and another commit to fix up the HelloWorld example)
> Stop using packaged elm

- LICENSE
- README.md
- bower.json
- examples/HelloWorld.elm
- index.js
- package.json
@avh4 feel free to merge if this seems to be working with your `elm-test` fork, and I'll publish to npm as `1.0.0`.
> Use elm-make on PATH instead of local dependency

- index.js
- package.json
- test/dependencies.js
- test/fixtures/ChildA.elm
- test/fixtures/ChildB.elm
- test/fixtures/NativeChild.js
- test/fixtures/NestedChild.elm
- test/fixtures/Parent.elm
- test/fixtures/ParentWithNestedDeps.elm
Adds a way to read dependencies.
> Read dependencies

- index.js
- package.json
> Use `cross-spawn` by default

- README.md
- index.js
- package.json
- test/dependencies.js
- test/fixtures/Parent.elm
- test/fixtures/ParentWithNestedDeps.elm
- test/fixtures/Test/ChildA.elm
- test/fixtures/Test/ChildB.elm
- test/fixtures/Test/Sample/NestedChild.elm
Should unblock fixing https://github.com/rtfeldman/elm-webpack-loader/issues
> Fix nested directory resolution

- test/compile.js
> Test `compileToString`

- index.js
- package.json
- test/compile.js
- test/dependencies.js
- test/fixtures/Bad.elm
This branch is based on https://github.com/rtfeldman/node-elm-compiler/pull/19, so ignore the first commit `acd6e7d`.
> Add tests for custom warn

- index.js
- test/compile.js
> Support passing --warn to Elm

- .gitignore
- .travis.yml
- README.md
- appveyor.yml
- bower.json
- examples/HelloWorld.elm
- examples/elm-package.json
- index.js
- package.json
- test/compile.js
- test/fixtures/Bad.elm
- test/fixtures/BasicWorker.elm
- test/fixtures/Parent.elm
- test/fixtures/ParentWithNestedDeps.elm
- test/fixtures/Test/ChildA.elm
- test/fixtures/Test/ChildB.elm
- test/fixtures/Test/Sample/NestedChild.elm
- test/fixtures/TypeError.elm
- test/fixtures/elm-package.json
- worker.js
Adds new `compileWorker`, which compiles and runs an `Elm.worker` instance and gives it to you, so you can subscribe to its ports.
> Compile to worker

- index.js
- package.json
- test/compile.js
- worker.js
In particular to avoid the `cross-spawn` warning
> Upgrade deps

- examples/HelloWorld.elm
I believe the following fixes are required to run the example using the instructions in the example section.
> Fixes example HelloWorld

- test/compile.js
this shows the bug described in #41 .
`compileToString` is run twice in a row, which sometimes fails, because the tempfile is gone.)
> example of race-condition when run twice in a row.

- .travis.yml
- appveyor.yml
- index.js
- test/compileSync.js
- test/fixtures/BasicWorker.elm
- test/fixtures/elm-package.json
Here it is, as mentionned here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!topic/elm-dev/gAyoEsQtHrU
Would be nice once merge so that I can fix the dependency there: https://github.com/yormi/babel-plugin-elm
The test `#compileWorker works with BasicWorker.elm` is failing as it was before this addition. I saw someone just opened an issue about it.
Let me know if there is anything !
> CompileSync

- index.js
> add support for --docs

- package.json
Resolves vulnerabilities flagged by `npm audit`
> Update dependencies: mocha, lodash

- examples/elm.json
Hi Richard!
Thanks for this project and doing the upgrade!
Here's a little help, I have upgraded the example to run with `0.19`
> Upgraded the example to use 0.19

- .travis.yml
- appveyor.yml
- index.js
- test/fixtures/elm.json
- worker.js
Sending this one along with #73 
This PR fixes all the tests.
> 0.19 tests

- src/worker.ts
Was ignored to make TypeScript compile.
> Remove superfluous argument

- src/index.ts
- test/compile.ts
Fixes #86.
Seemingly related issue about the compiler not handling parallel compilations: https://github.com/elm/compiler/issues/1853
> Use sequential compilation instead of parallel
